<?php $_creditmemo = $this->getCreditmemo() ?>
<?php $_order      = $this->getOrder() ?>
<?php if ($_creditmemo && $_order): ?>
<?php $i=0; $count = 1; foreach ($_creditmemo->getAllItems() as $_item): ?>
<?php if($_item->getOrderItem()->getParentItem()) continue; else $i++; ?>
<?php if($count > 1):?>
----------------
<?php endif;?>
<?php echo $this->getItemHtml($_item) . "\r\n" ?>
<?php $count++ ?>
<?php $qty += $_item->getQty()*1;?>
<?php endforeach; ?>
****************************************************************
合計商品数:   <?php echo ($qty); ?>(個)
<?php echo $this->getChildHtml('creditmemo_totals');?>
<?php endif; ?>
